### ISSUE TITLE
Use get() to query hyperlink url?

### ISSUE THREAD

**Issue by mortona42** [mgibbs189/cfs-hyperlink#1]
I used $cfs->get('url'), which outputs a formatted <a> tag.  I need to do things like add my own class, is it possible to retrieve just the URL using CFS methods, or do I need to use something else?

**Comment by mgibbs189** [comment]
FYI - there's a new "Format" option that controls whether the value is output as an HTML link or a PHP array.

**Comment by robneu** [comment]
Sweet! :100:
